#!/usr/bin/env python3
"""Generate deterministic, SDK-neutral C pin tables from the reviewed H2 export."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
MODEL_PATH = REPO_ROOT / "config" / "bsp_generation_input.json"
GPIO_CONTACT_RE = re.compile(r"GPIO([0-9]+)")
PA_CONTACT_RE = re.compile(r"PA([0-9]+)(?:_[A-Za-z0-9_]+)?")


def c_string(value: str | None) -> str:
    if value is None:
        return "NULL"
    return json.dumps(value, ensure_ascii=True)


def contact_number(domain: str, contact: str) -> int:
    matcher = GPIO_CONTACT_RE if domain in {"S3", "C5", "RP"} else PA_CONTACT_RE
    match = matcher.fullmatch(contact)
    if match is None:
        raise ValueError(f"cannot parse contact {domain}.{contact}")
    return int(match.group(1))


def guard(path: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "_", path).upper()


def render_types_header(relative: str) -> str:
    include_guard = guard(relative)
    return f"""/* Generated by tools/generate_hardware_bsp.py; do not edit. */
#ifndef {include_guard}
#define {include_guard}

#include <stddef.h>
#include <stdint.h>

typedef enum {{
    L2_HW_DIRECTION_INPUT = 0,
    L2_HW_DIRECTION_OUTPUT = 1,
    L2_HW_DIRECTION_INPUT_OUTPUT = 2,
    L2_HW_DIRECTION_OPEN_DRAIN = 3,
}} l2_hw_direction_t;

typedef enum {{
    L2_HW_POLARITY_UNSPECIFIED = 0,
    L2_HW_POLARITY_ACTIVE_LOW = 1,
}} l2_hw_polarity_t;

typedef struct {{
    const char *instance;
    const char *contact;
    const char *net;
    const char *controller;
    const char *strap_proof;
    const char *sharing_proof;
    const char *reset_proof;
    const char *const *peers;
    uint16_t contact_number;
    uint16_t peer_count;
    l2_hw_direction_t direction;
    l2_hw_polarity_t polarity;
}} l2_hw_pin_t;

typedef struct {{
    const char *domain;
    const char *instance;
    const char *mpn;
    const l2_hw_pin_t *pins;
    uint16_t pin_count;
}} l2_hw_domain_t;

#endif
"""


DIRECTION_ENUM = {
    "i": "L2_HW_DIRECTION_INPUT",
    "o": "L2_HW_DIRECTION_OUTPUT",
    "io": "L2_HW_DIRECTION_INPUT_OUTPUT",
    "od": "L2_HW_DIRECTION_OPEN_DRAIN",
}


def render_domain_header(relative: str, domain: dict, output_stem: str) -> str:
    include_guard = guard(relative)
    domain_token = domain["domain"]
    constants = "\n".join(
        f"    L2_HW_{domain_token}_{pin['net']} = "
        f"{contact_number(domain_token, pin['contact'])},"
        for pin in domain["pins"]
    )
    return f"""/* Generated by tools/generate_hardware_bsp.py; do not edit. */
#ifndef {include_guard}
#define {include_guard}

#include "leshy2/hardware/bsp_types.h"

enum {{
{constants}
    L2_HW_{domain_token}_PIN_COUNT = {len(domain['pins'])},
}};

extern const l2_hw_pin_t l2_hw_{output_stem}_pins[L2_HW_{domain_token}_PIN_COUNT];
extern const l2_hw_domain_t l2_hw_{output_stem}_domain;

#endif
"""


def render_domain_source(domain: dict, output_stem: str) -> str:
    domain_token = domain["domain"]
    peer_arrays: list[str] = []
    pin_rows: list[str] = []
    for index, pin in enumerate(domain["pins"]):
        peer_name = f"l2_hw_{output_stem}_pin_{index}_peers"
        peers = ",\n".join(f"    {c_string(peer)}" for peer in pin["peers"])
        peer_arrays.append(
            f"static const char *const {peer_name}[] = {{\n{peers}\n}};"
        )
        polarity = (
            "L2_HW_POLARITY_ACTIVE_LOW"
            if pin["net"].endswith("_N")
            else "L2_HW_POLARITY_UNSPECIFIED"
        )
        pin_rows.append(
            "    {\n"
            f"        .instance = {c_string(pin['instance'])},\n"
            f"        .contact = {c_string(pin['contact'])},\n"
            f"        .net = {c_string(pin['net'])},\n"
            f"        .controller = {c_string(pin['controller'])},\n"
            f"        .strap_proof = {c_string(pin.get('strap_proof'))},\n"
            f"        .sharing_proof = {c_string(pin.get('sharing_proof'))},\n"
            f"        .reset_proof = {c_string(pin.get('reset_proof'))},\n"
            f"        .peers = {peer_name},\n"
            f"        .contact_number = UINT16_C({contact_number(domain_token, pin['contact'])}),\n"
            f"        .peer_count = UINT16_C({len(pin['peers'])}),\n"
            f"        .direction = {DIRECTION_ENUM[pin['direction']]},\n"
            f"        .polarity = {polarity},\n"
            "    },"
        )

    return f"""/* Generated by tools/generate_hardware_bsp.py; do not edit. */
#include "leshy2/hardware/{output_stem}_bsp.h"

{chr(10).join(peer_arrays)}

const l2_hw_pin_t l2_hw_{output_stem}_pins[L2_HW_{domain_token}_PIN_COUNT] = {{
{chr(10).join(pin_rows)}
}};

const l2_hw_domain_t l2_hw_{output_stem}_domain = {{
    .domain = {c_string(domain['domain'])},
    .instance = {c_string(domain['instance'])},
    .mpn = {c_string(domain['mpn'])},
    .pins = l2_hw_{output_stem}_pins,
    .pin_count = UINT16_C(L2_HW_{domain_token}_PIN_COUNT),
}};
"""


def sha256_text(content: str) -> str:
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


def render_all(model: dict, contract: dict) -> dict[str, str]:
    outputs = model["outputs"]
    rendered: dict[str, str] = {}
    types_path = outputs["common_types_header"]
    rendered[types_path] = render_types_header(types_path)
    domains = {domain["domain"]: domain for domain in contract["bsp"]["domains"]}
    for planned in model["domains"]:
        domain = domains[planned["domain"]]
        stem = planned["output_stem"]
        header_path = outputs["domain_header_pattern"].format(output_stem=stem)
        source_path = outputs["domain_source_pattern"].format(output_stem=stem)
        rendered[header_path] = render_domain_header(header_path, domain, stem)
        rendered[source_path] = render_domain_source(domain, stem)

    manifest_files = []
    for relative, content in sorted(rendered.items()):
        kind = "header" if relative.endswith(".h") else "source"
        stem = Path(relative).stem.removesuffix("_bsp")
        domain = next(
            (row["domain"] for row in model["domains"] if row["output_stem"] == stem),
            "COMMON",
        )
        manifest_files.append(
            {
                "path": relative,
                "kind": kind,
                "domain": domain,
                "bytes": len(content.encode("utf-8")),
                "sha256": sha256_text(content),
            }
        )
    manifest = {
        "schema_version": 1,
        "stage": "F2.3.1",
        "status": "generated",
        "producer": "tools/generate_hardware_bsp.py",
        "source_contract": model["source_contract"],
        "source_sha256": model["source_identity"]["source_sha256"],
        "generation_model": "config/bsp_generation_input.json",
        "allocated_contacts": model["expected_counts"]["allocated_contacts"],
        "files": manifest_files,
        "claims": {
            "generated_files_are_hand_edited": False,
            "target_projects_consume_generated_sources": False,
            "target_configure_run": False,
            "target_builds_run": False,
        },
    }
    rendered[outputs["manifest"]] = json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"
    return rendered


def validate_input() -> bool:
    result = subprocess.run(
        ("python3", "tools/validate_bsp_generation_input.py"),
        cwd=REPO_ROOT,
        check=False,
    )
    return result.returncode == 0


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()

    if not validate_input():
        return 1
    model = json.loads(MODEL_PATH.read_text(encoding="utf-8"))
    contract = json.loads((REPO_ROOT / model["source_contract"]).read_text(encoding="utf-8"))
    expected = render_all(model, contract)

    if args.write:
        for relative, content in expected.items():
            path = REPO_ROOT / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"wrote {relative}")
        return 0

    stale = []
    for relative, content in expected.items():
        path = REPO_ROOT / relative
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            stale.append(relative)
    if stale:
        for relative in stale:
            print(f"stale: {relative}", file=sys.stderr)
        return 1
    print(
        "generated BSP OK: 11 generated C/header files, 5 domains and "
        "125 contacts match H2 byte-for-byte"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
