#!/usr/bin/env python3
"""Generate the deterministic six-domain R2 BSP boundary from H1-R2.31."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MODEL_PATH = ROOT / "config" / "f2_r2_bsp_generation.json"
DIRECTION = {
    "in": "L2_R2_DIRECTION_INPUT",
    "out": "L2_R2_DIRECTION_OUTPUT",
    "io": "L2_R2_DIRECTION_INPUT_OUTPUT",
    "od": "L2_R2_DIRECTION_OPEN_DRAIN",
    "reserve": "L2_R2_DIRECTION_RESERVED",
}
MAPPING = {
    "exact_pins": "L2_R2_MAPPING_EXACT_PINS",
    "partial_exact_pins": "L2_R2_MAPPING_PARTIAL_EXACT_PINS",
    "gpio_groups": "L2_R2_MAPPING_GPIO_GROUPS",
    "identity_only": "L2_R2_MAPPING_IDENTITY_ONLY",
}


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def c_string(value: str | None) -> str:
    return "NULL" if value is None else json.dumps(value, ensure_ascii=True)


def token(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "_", value).upper()


def include_guard(relative: str) -> str:
    return token(relative)


def render_types(relative: str) -> str:
    guard = include_guard(relative)
    return f"""/* Generated by tools/generate_f2_r2_bsp.py; do not edit. */
#ifndef {guard}
#define {guard}

#include <stddef.h>
#include <stdint.h>

typedef enum {{
    L2_R2_DIRECTION_INPUT = 0,
    L2_R2_DIRECTION_OUTPUT = 1,
    L2_R2_DIRECTION_INPUT_OUTPUT = 2,
    L2_R2_DIRECTION_OPEN_DRAIN = 3,
    L2_R2_DIRECTION_RESERVED = 4,
}} l2_r2_direction_t;

typedef enum {{
    L2_R2_MAPPING_EXACT_PINS = 0,
    L2_R2_MAPPING_PARTIAL_EXACT_PINS = 1,
    L2_R2_MAPPING_GPIO_GROUPS = 2,
    L2_R2_MAPPING_IDENTITY_ONLY = 3,
}} l2_r2_mapping_t;

typedef struct {{
    const char *net;
    const char *peripheral;
    const char *endpoint;
    const char *gate;
    uint8_t gpio;
    l2_r2_direction_t direction;
}} l2_r2_pin_t;

typedef struct {{
    const char *role;
    uint64_t gpio_mask;
    uint8_t gpio_count;
}} l2_r2_gpio_group_t;

typedef struct {{
    const char *id;
    const char *mpn;
    const char *role;
    const l2_r2_pin_t *pins;
    const l2_r2_gpio_group_t *groups;
    uint16_t pin_count;
    uint16_t group_count;
    l2_r2_mapping_t mapping;
}} l2_r2_domain_t;

#endif
"""


def render_header(relative: str, planned: dict, pins: list[dict], groups: list[dict]) -> str:
    guard = include_guard(relative)
    domain = token(planned["id"])
    pin_constants = ""
    if pins:
        pin_constants = "\n" + "\n".join(
            f"    L2_R2_{domain}_{token(pin['net'])} = {pin['gpio']},"
            for pin in pins
        )
    return f"""/* Generated by tools/generate_f2_r2_bsp.py; do not edit. */
#ifndef {guard}
#define {guard}

#include "leshy2/r2/hardware/bsp_types.h"

enum {{{pin_constants}
    L2_R2_{domain}_PIN_COUNT = {len(pins)},
    L2_R2_{domain}_GROUP_COUNT = {len(groups)},
}};

extern const l2_r2_domain_t l2_r2_{planned['id']}_domain;

#endif
"""


def gpio_mask(gpios: list[int]) -> int:
    value = 0
    for gpio in gpios:
        if not isinstance(gpio, int) or gpio < 0 or gpio > 63:
            raise ValueError(f"GPIO outside uint64 mask: {gpio!r}")
        value |= 1 << gpio
    return value


def render_source(planned: dict, identity: dict, pins: list[dict], groups: list[dict]) -> str:
    domain_id = planned["id"]
    pin_block = ""
    pin_pointer = "NULL"
    if pins:
        rows = []
        for pin in pins:
            rows.append(
                "    {\n"
                f"        .net = {c_string(pin['net'])},\n"
                f"        .peripheral = {c_string(pin['peripheral'])},\n"
                f"        .endpoint = {c_string(pin.get('endpoint'))},\n"
                f"        .gate = {c_string(pin.get('gate'))},\n"
                f"        .gpio = UINT8_C({pin['gpio']}),\n"
                f"        .direction = {DIRECTION[pin['direction']]},\n"
                "    },"
            )
        pin_block = (
            f"static const l2_r2_pin_t l2_r2_{domain_id}_pins[] = {{\n"
            + "\n".join(rows)
            + "\n};\n\n"
        )
        pin_pointer = f"l2_r2_{domain_id}_pins"

    group_block = ""
    group_pointer = "NULL"
    if groups:
        rows = []
        for group in groups:
            rows.append(
                "    {\n"
                f"        .role = {c_string(group['role'])},\n"
                f"        .gpio_mask = UINT64_C(0x{gpio_mask(group['gpios']):016X}),\n"
                f"        .gpio_count = UINT8_C({len(group['gpios'])}),\n"
                "    },"
            )
        group_block = (
            f"static const l2_r2_gpio_group_t l2_r2_{domain_id}_groups[] = {{\n"
            + "\n".join(rows)
            + "\n};\n\n"
        )
        group_pointer = f"l2_r2_{domain_id}_groups"

    return f"""/* Generated by tools/generate_f2_r2_bsp.py; do not edit. */
#include "leshy2/r2/hardware/{domain_id}_bsp.h"

{pin_block}{group_block}const l2_r2_domain_t l2_r2_{domain_id}_domain = {{
    .id = {c_string(domain_id)},
    .mpn = {c_string(identity['mpn'])},
    .role = {c_string(identity['role'])},
    .pins = {pin_pointer},
    .groups = {group_pointer},
    .pin_count = UINT16_C(L2_R2_{token(domain_id)}_PIN_COUNT),
    .group_count = UINT16_C(L2_R2_{token(domain_id)}_GROUP_COUNT),
    .mapping = {MAPPING[planned['mapping']]},
}};
"""


def render_all(model: dict, hardware: dict) -> dict[str, str]:
    identities = {row["id"]: row for row in hardware["domains"]}
    expected_ids = [row["id"] for row in model["domains"]]
    if list(identities) != expected_ids:
        raise ValueError("hardware projection domain order differs from generation model")

    include_root = model["outputs"]["include_root"]
    source_root = model["outputs"]["source_root"]
    rendered: dict[str, str] = {}
    types_path = f"{include_root}/leshy2/r2/hardware/bsp_types.h"
    rendered[types_path] = render_types(types_path)
    inventory: list[dict] = []

    for planned in model["domains"]:
        domain_id = planned["id"]
        pins = (
            hardware.get(planned.get("source_key", ""), [])
            if planned["mapping"] in {"exact_pins", "partial_exact_pins"}
            else []
        )
        groups = hardware.get(planned.get("source_key", ""), []) if planned["mapping"] == "gpio_groups" else []
        header = f"{include_root}/leshy2/r2/hardware/{domain_id}_bsp.h"
        source = f"{source_root}/{domain_id}_bsp.c"
        rendered[header] = render_header(header, planned, pins, groups)
        rendered[source] = render_source(planned, identities[domain_id], pins, groups)
        inventory.append(
            {
                "id": domain_id,
                "mapping": planned["mapping"],
                "pins": len(pins),
                "groups": len(groups),
                "header": header,
                "source": source,
                "symbol": f"l2_r2_{domain_id}_domain",
            }
        )

    files = [
        {
            "path": path,
            "bytes": len(content.encode("utf-8")),
            "sha256": hashlib.sha256(content.encode("utf-8")).hexdigest(),
        }
        for path, content in sorted(rendered.items())
    ]
    manifest = {
        "schema_version": 1,
        "stage": "F2-R2.3",
        "status": "generated",
        "producer": "tools/generate_f2_r2_bsp.py",
        "source": model["source"],
        "generation_model": str(MODEL_PATH.relative_to(ROOT)),
        "domains": inventory,
        "files": files,
        "claims": {
            "deterministic": True,
            "one_descriptor_per_domain": True,
            "unpublished_pin_assignments_invented": False,
            "target_configure_run": False,
            "target_build_run": False,
        },
    }
    rendered[model["outputs"]["manifest"]] = json.dumps(
        manifest, indent=2, ensure_ascii=False
    ) + "\n"
    return rendered


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()

    model = json.loads(MODEL_PATH.read_text(encoding="utf-8"))
    source_path = ROOT / model["source"]["path"]
    if digest(source_path) != model["source"]["sha256"]:
        print("source projection hash differs from F2-R2.3 lock", file=sys.stderr)
        return 1
    hardware = json.loads(source_path.read_text(encoding="utf-8"))
    try:
        expected = render_all(model, hardware)
    except (KeyError, TypeError, ValueError) as error:
        print(f"invalid F2-R2.3 input: {error}", file=sys.stderr)
        return 1

    if args.write:
        for relative, content in expected.items():
            path = ROOT / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"wrote {relative}")
        return 0

    stale = []
    for relative, content in expected.items():
        path = ROOT / relative
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            stale.append(relative)
    if stale:
        for relative in stale:
            print(f"stale: {relative}", file=sys.stderr)
        return 1
    print("F2-R2.3 generated BSP OK: 6 domains, 13 C/header files, H1-R2.31 hash locked")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
