#!/usr/bin/env python3
"""Run the complete F2.3 generated-H2-BSP boundary review."""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
REVIEW_PATH = REPO_ROOT / "config" / "f2_3_review.json"
MANIFEST_PATH = REPO_ROOT / "generated" / "source_manifest.json"


def fail(message: str, output: str = "") -> int:
    if output:
        sys.stdout.write(output)
    print(f"ERROR: {message}", file=sys.stderr)
    return 1


def run(command: tuple[str, ...], expected: str) -> tuple[bool, str]:
    result = subprocess.run(
        command,
        cwd=REPO_ROOT,
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    return result.returncode == 0 and expected in result.stdout, result.stdout


def main() -> int:
    review = json.loads(REVIEW_PATH.read_text(encoding="utf-8"))
    if review.get("stage") != "F2.3.3" or review.get("status") != "reviewed":
        return fail("F2.3.3 review artifact is not reviewed")
    expected_evidence = {
        "hardware_domains": 5,
        "allocated_contacts": 125,
        "unique_nets": 112,
        "transports": 4,
        "signal_groups": 10,
        "generated_files": 11,
        "generated_bytes": 80864,
        "target_consumers": 5,
        "strict_c17_table_compilations": 5,
    }
    if review.get("evidence") != expected_evidence:
        return fail("F2.3 evidence counts changed")
    expected_claims = {
        "hardware_export_matches_sibling_repository": True,
        "generated_outputs_are_byte_reproducible": True,
        "all_generated_tables_compile_as_strict_c17": True,
        "one_owner_per_generated_domain": True,
        "temporary_or_hand_authored_pins": False,
        "target_configure_run": False,
        "target_builds_run": False,
        "target_emulators_run": False,
    }
    if review.get("claims") != expected_claims:
        return fail("F2.3 review claims changed")

    checks = (
        (("python3", "tools/review_f2_2.py"), "F2.2 integrated review OK"),
        (
            ("python3", "tools/import_hardware_contract.py", "--check"),
            "firmware HW/FW and BSP contracts match",
        ),
        (
            ("python3", "tools/validate_bsp_generation_input.py"),
            "BSP generation input OK",
        ),
        (
            ("python3", "tools/generate_hardware_bsp.py", "--check"),
            "generated BSP OK",
        ),
        (
            ("python3", "tools/check_source_layout.py"),
            "11 generated BSP files",
        ),
        (
            ("python3", "tools/check_bsp_target_consumption.py"),
            "BSP target consumption OK",
        ),
    )
    for command, expected in checks:
        ok, output = run(command, expected)
        if not ok:
            return fail(f"check failed: {' '.join(command)}", output)

    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    files = manifest.get("files", [])
    if len(files) != expected_evidence["generated_files"]:
        return fail("generated file count differs from F2.3 evidence")
    if sum(row.get("bytes", 0) for row in files) != expected_evidence["generated_bytes"]:
        return fail("generated byte count differs from F2.3 evidence")

    compiler = shutil.which("cc")
    if compiler is None:
        return fail("host C compiler is required to validate generated tables")
    sources = sorted((REPO_ROOT / "generated/hardware/src").glob("*_bsp.c"))
    if len(sources) != expected_evidence["strict_c17_table_compilations"]:
        return fail("generated domain-source count changed")
    compile_command = (
        compiler,
        "-std=c17",
        "-Wall",
        "-Wextra",
        "-Werror",
        "-pedantic",
        "-Igenerated/hardware/include",
        "-fsyntax-only",
        *(str(path.relative_to(REPO_ROOT)) for path in sources),
    )
    result = subprocess.run(
        compile_command,
        cwd=REPO_ROOT,
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    if result.returncode != 0:
        return fail("generated tables do not compile as strict C17", result.stdout)

    print(
        "F2.3 integrated review OK: sibling H2 matches; 125 contacts in 11 "
        "byte-reproducible files compile as strict C17 and map one-to-one to "
        "5 targets; 0 configure/build/emulator executions claimed"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
